# imports
import os
import pandas as pd

# set configfile with samplenames
configfile: "config.yaml"

# include snakefiles
include: "bowtie.smk"

# Load the metadata file
metadata = pd.read_csv(config['metadata_file_path'], usecols=['Run'])


# Create a list of run ids
samples = metadata['Run'].tolist()

# Define samples
SAMPLES = config.get('samples', samples)

wildcard_constraints:
    sample='\w+',

rule all:
    input:
        expand("check/{sample}_done.txt", sample=SAMPLES,)