# set the list of files
SAMPLE, = glob_wildcards('../sourmash/sig_files/vOTU_fasta/highqual/split_1/{filename}.fa')
DB_AMR = '/home/amhorst/mambaforge/envs/amrfinderplus/share/amrfinderplus/data/2023-11-15.1/'


# final output
rule all:
    input:
        expand('AMRFINDER_result/{filename}.tsv', filename=SAMPLE),    


# run prodigal to predict proteins for AMRfinder
rule prodigal:
    input:
       fa='../sourmash/sig_files/vOTU_fasta/highqual/split_1/{sample}.fa',
    output:
        faa=touch('prot_files/{sample}.faa'),
    conda: 
        "prodigal.yml"
    threads: 1
    shell:
        """
        prodigal -q -i {input.fa} -a {output.faa} -p meta
        """

# run amrfinder using x threads against protein. (HMM + blastp)
rule amrfinder:
    input:
       faa='prot_files/{sample}.faa',
    output:
        csv=touch('AMRFINDER_result/{sample}.tsv'),
    conda: 
        "amrfinder.env.yml"
    threads: 1
    shell:
        """
        amrfinder -p {input.faa} --threads {threads} \
        -o {output.csv} --plus --database {DB_AMR}
        """
